### ISSUE TITLE
Broken links to Piazza site 

### ISSUE THREAD

**Issue by damianrt** [FRB-Howard-U/ECOG-314#3]
The links to the piazza site are broken on the home page (https://frb-howard-u.github.io/ECOG-314/) and other pages.

- "Discussion" link at the top of the home page.
- "Course Piazza site" link at the bottom of the home page

The actual site link has a misspelling ("univeristy" not "university")
https://piazza.com/federal_reserve_boardhoward_univeristy/fall2017/ecog314econ181

**Comment by mondorescue** [comment]
Replaced URL to point to hashed version (https://piazza.com/class/j6f9vjo5q5v4lf?cid=6), which is static, until we sort out getting a better URL.
