### ISSUE TITLE
No setup instructions

### ISSUE THREAD

**Issue by damianrt** [FRB-Howard-U/ECOG-314#4]
Clicking on the "setup" link on the home page under the "Schedule" heading (https://frb-howard-u.github.io/ECOG-314/) leads to an empty html page. The setup link at the top of the page goes to a separate PDF.  We should add a link to the pdf in the html version.  We should also consider bringing the pdf content into the html page, at least so ti covers RStudio and R. Other software to consider adding
1. Git: install instructions, instructions for cloning course materials locally
2. gcc compiler, for students having trouble installing packages
3. A test script, something that instructors or students can copy-paste to test their machines are set up correctly

**Comment by mondorescue** [comment]
PDF on setup instructions for students, now posted.
